### ISSUE TITLE
[speech-to-text]  Fails during executing - npm run build

### ISSUE THREAD

**Issue by prasanta303** [watson-developer-cloud/speech-to-text-nodejs#100]
I have downloaded and tried to "npm install" it's failing with message,
 error: { [Error: not found: git] code: 'ENOGIT'}
Do I need to Git 2.8.1 installer for windows 7?

Below error in command line is given,

![npm install err](https://cloud.githubusercontent.com/assets/18462152/14751278/b9d84998-08e6-11e6-8bd8-e4ba0f2dbc25.png)

**Comment by prasanta303** [comment]
It has been resolved by doing "npm install -g npm-install-missing@0.1.4
But after that when I do "npm run build" it throws error :
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! SpeechToTextBrowserStarterApp@1.0.1 build: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the SpeechToTextBrowserStarterApp@1.0.1 build script 'npm run
 build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the SpeechToTextBrowserSt
arterApp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs SpeechToTextBrowserStarterApp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls SpeechToTextBrowserStarterApp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Prasanta\Official\IBM\IDEA\NBA\speech-to-text-nodejs-master\npm-
debug.log

Log is attached herewith.
[npm-debug.txt](https://github.com/watson-developer-cloud/speech-to-text-nodejs/files/232417/npm-debug.txt)

**Comment by nfriedly** [comment]
Hi @prasanta303 

Can you start over fresh (delete the `node_modules` directory and `npm-debug.log`, run `npm install`) and then give me the complete logs from the command line and the new `npm-debug.log` if it gets recreated? (The second error overwrote the log for the first one, which is what I need to see.)

**Comment by prasanta303** [comment]
The issue is now resolved. So closing it.
After doing as you said, did `npm start` and from browser, opened http://localhost:3000/ and it runs properly.
