### ISSUE TITLE
Using the librery

### ISSUE THREAD

**Issue by elgamersitom** [watson-developer-cloud/speech-to-text-nodejs#101]
Hello, 

I was wondering if the use of BlueMix is necessary to develop over the speech to text API.

If the answer is yes, is the free plan enough to use the API?. Hope some of you with the experience on development can help me.

Bye

**Comment by nfriedly** [comment]
Hi,

A bluemix account is required to access the service, but once things are set up in bkuemix and you get the service credentials, you can then run the API locally of on another hosting provider.
