### ISSUE TITLE
A real-time captioning service is possible with this...

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/speech-to-text-nodejs#107]

**Comment by nfriedly** [comment]
Yes.

**Comment by johnfelipe** [comment]
how can made it

**Comment by nfriedly** [comment]
That's where the hard work comes in ;)

You can check out https://audio-analysis-application-starter-kit.mybluemix.net/dashboard?v=gkjW9PZBRfk for a nice example though.

**Comment by johnfelipe** [comment]
is possible do it for spanish?

**Comment by nfriedly** [comment]
Yep. See the documentation at http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/speech-to-text/ for a full list of supported languages.

**Comment by johnfelipe** [comment]
Is possible with hangout on air url?

2016-05-31 13:43 GMT-05:00 Nathan Friedly <notifications@github.com>:

**Comment by nfriedly** [comment]
Maybe, but I'm not sure how.
