### ISSUE TITLE
how can i add again npm run build

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/speech-to-text-nodejs#108]
I need do change and i need `npm run build` how can i add again?

**Comment by nfriedly** [comment]
Why? It's not needed anymore, the js is compiled on the fly now.

**Comment by johnfelipe** [comment]
i need for show only spanish language, or how can i do that?

**Comment by nfriedly** [comment]
I think you'll want to edit https://github.com/watson-developer-cloud/speech-to-text-nodejs/blob/master/src/data/models.json but there may also be other changes to make.

**Comment by johnfelipe** [comment]
in `/home/felipe/speech-to-text-nodejs/src/models.js`
i have this:

##
	 var spansihModels = [];
	   for(var index = 0; index < sorted.length; index++) {
	   var model = sorted[index];
	   if(model.language == 'es-ES') {
		 spansihModels.push(model);
	   }
	}
	response.models=spansihModels;	
##

and `/home/felipe/speech-to-text-nodejs/src/data/models.json`

i have this

##
{
   "models": [
      {
         "url": "https://stream.watsonplatform.net/speech-to-text/api/v1/models/es-ES_BroadbandModel", 
         "rate": 16000, 
         "name": "es-ES_BroadbandModel", 
         "language": "es-ES", 
         "description": "Spanish broadband model."
      }, 
      {
         "url": "https://stream.watsonplatform.net/speech-to-text/api/v1/models/es-ES_NarrowbandModel", 
         "rate": 8000, 
         "name": "es-ES_NarrowbandModel", 
         "language": "es-ES", 
         "description": "Spanish narrowband model."
      }
   ]
}
##

how can i recompile?

**Comment by nfriedly** [comment]
`npm start` and then open your browser and go to http://localhost:3000/ . It automatically re compiles on the fly now - there is no separate build/compile step.

**Comment by johnfelipe** [comment]
`pm2 reload server.js`

and not works

http://181.135.63.86:3002/

**Comment by nfriedly** [comment]
If you click the dropdown, the options are correct, so that part works. It's just retaining the default English value. It looks like the default is getting set in https://github.com/watson-developer-cloud/speech-to-text-nodejs/blob/master/src/index.js

**Comment by nfriedly** [comment]
It's only showing two models in the dropdown:

![screen shot 2016-06-01 at 3 36 19 pm](https://cloud.githubusercontent.com/assets/114976/15723060/adad50a4-280e-11e6-8bd5-b68025d5cdee.png)


The default is set to English, but once another model is selected, that one disappears:

![screen shot 2016-06-01 at 3 36 27 pm](https://cloud.githubusercontent.com/assets/114976/15723071/bb08e33a-280e-11e6-84ae-9dc8141422ec.png)

If you change the default to one of those two, it should then only ever show those two.

**Comment by johnfelipe** [comment]
i delete my cookies in firefox and chrome but is not show like that, how can i do additional?

**Comment by nfriedly** [comment]
Try private/incognito mode or deleting your cache maybe?

**Comment by johnfelipe** [comment]
![incognito](https://cloud.githubusercontent.com/assets/428820/15725453/a36f94dc-2811-11e6-8299-c866fe895706.png)

dont work

**Comment by nfriedly** [comment]
I don't know then; this about the the limit of the support I can provide.

**Comment by johnfelipe** [comment]
What is version of your chrome?

**Comment by johnfelipe** [comment]
What version is yours...
