### ISSUE TITLE
The "word alternative" section of the GUI renders blurry on the Retina displays.

### ISSUE THREAD

**Issue by petrn3** [watson-developer-cloud/speech-to-text-nodejs#110]
Rendering on any HiDPI screen can potentially be affected. 

It looks like the devicePixelRatio and the backingStoreRatio are not used correctly for the "word alternative" canvas.

BTW: the "keywords section" renders correctly so a solution is most likely available within the project already.

**Comment by nfriedly** [comment]
Hey @petrn3, thanks for pointing this out. The keywords section is just regular HTML, so that's why it works properly.

I don't have a lot of experience with `<canvas>`. @leonrch does the canvas pixel ratio sound like something reasonably easy to fix?

**Comment by leonrch** [comment]
Please try to replace the current implementation of
 $(window).resize(function(), which resides at the bottom of
src/views/displaymetadata.js with the following one:

$(window).resize(function() {
  var dpr = window.devicePixelRatio || 1;
  var bsr = ctx.webkitBackingStorePixelRatio ||
    ctx.mozBackingStorePixelRatio ||
    ctx.msBackingStorePixelRatio ||
    ctx.oBackingStorePixelRatio ||
    ctx.backingStorePixelRatio || 1;

  var ratio = dpr / bsr;
  console.log('dpr/bsr =', ratio);
  var w = $("#canvas").width();
  var h = $("#canvas").height();
  canvas.width = w * ratio;
  canvas.height = h * ratio;
  ctx.setTransform(ratio, 0, 0, ratio, 0, 0);
  draw();
});

**Comment by leonrch** [comment]
Please try to replace the current implementation of `$(window).resize(function()`, which resides at the bottom of **src/views/displaymetadata.js** with the following one:

`$(window).resize(function() {`
 `var dpr = window.devicePixelRatio || 1;`
 `var bsr = ctx.webkitBackingStorePixelRatio ||`
 `ctx.mozBackingStorePixelRatio ||`
 `ctx.msBackingStorePixelRatio ||`
 `ctx.oBackingStorePixelRatio ||`
 `ctx.backingStorePixelRatio || 1;`
 `var ratio = dpr / bsr;`
 `console.log('dpr/bsr =', ratio);`
 `var w = $("#canvas").width();`
 `var h = $("#canvas").height();`
 `canvas.width = w * ratio;`
 `canvas.height = h * ratio;`
 `ctx.setTransform(ratio, 0, 0, ratio, 0, 0);`
 `draw();`
`});`

**Comment by germanattanasio** [comment]
@leonrch can you create a pull request with this change ?

**Comment by nfriedly** [comment]
Thanks @leonrch - it's looking sharp now!
