### ISSUE TITLE
Watson Speech to Text Service Failed to Work on Safari 9.x

### ISSUE THREAD

**Issue by timelyxyz** [watson-developer-cloud/speech-to-text-nodejs#117]
Hi Team,

I am working on a iOS web app. I found this node.js based SDK can't work on safari 9.x. After investigation, I've found the following issues:

1. Safari Const declarations are not supported in strict mode.
2. Websocket failed with _"Invalid UTF-8 sequence in header value"_  when request or response contains any empty header, such as "Content-Type".  
![image](https://cloud.githubusercontent.com/assets/1519257/16477057/03bd26f4-3ec1-11e6-8f20-2635c0cfd727.png)

Per above two issues, I did some modification on the local JavaScript code

1. change "const" to "var"
2. as for the blank header in request for token,  I add blank check before post it
```
if ($('meta[name="ct"]').attr('content').length > 0) {
    tokenRequest.setRequestHeader('csrf-token',$('meta[name="ct"]').attr('content'));
}
```
But for the blank header in response from Watson server, I can do nothing =(
Is there any way to fix this? Thanks!

Here's some reference for the second issue
1. https://bugs.webkit.org/show_bug.cgi?id=139298
2. https://bugs.chromium.org/p/chromium/issues/detail?id=380075

**Comment by germanattanasio** [comment]
The problem is that the token we use exceeded the url limitation from safari.

**Comment by nfriedly** [comment]
Hi @timelyxyz,

Thanks for looking into this. We've also looked into the second one but were unable to find a workable solution. So it's up to Apple to fix that one.

I also believe there are other issues for Safari on iOS, besides that one.

For iOS specifically, we recommend that you use our [iOS SDK](https://github.com/watson-developer-cloud/ios-sdk)

For web apps in general, we currently recommend the [Speech JS SDK](https://github.com/watson-developer-cloud/speech-javascript-sdk) as it significantly reduces the amount of code necessary. It still won't work in Safari but it does work in Chrome and Firefox on Android. (I have plans to update this app to use the SDK, but just haven't had the time yet.)

**Comment by timelyxyz** [comment]
Hi @germanattanasio and @nfriedly , thanks for your tip. But I'm not familiar with iOS skills, I'll try integrate java SDK with Web Audio API.
