### ISSUE TITLE
the app does not seem to work in mac when using firefox

### ISSUE THREAD

**Issue by daniel-bolanos** [watson-developer-cloud/speech-to-text-nodejs#118]
Using the app in firefox from Mac does not seem to work for all users. I do not have a mac, @nfriedly @germanattanasio can you please take a look and see if it works for you? Apparently the issue gets fixed if restarting firefox... sorry I do not have more details

Dani

**Comment by nfriedly** [comment]
Confirmed, Firefox 45 on mac :(

This must be a new development, it's always worked for me in the past. I'll look through what's changed recently.

**Comment by daniel-bolanos** [comment]
thanks Nathan, I'm glad that you were able to reproduce it

Dani

**Comment by daniel-bolanos** [comment]
btw. one user who had this issue restarted firefox disabling addoons and it started working again... just in case this is of any help

**Comment by nfriedly** [comment]
OK, I've got to head out for now, I'll come back to this when I can though. Haven't figured much out yet.

**Comment by daniel-bolanos** [comment]
thanks

**Comment by nfriedly** [comment]
So, this is frustrating. My firefox crashed this morning and I haven't been able to reproduce it since. I'm going to leave it open tonight and try again tomorrow.

**Comment by daniel-bolanos** [comment]
same thing happened to a colleague, he restarted and it started working fine again. Maybe something that builds up over time...

**Comment by nfriedly** [comment]
Firefox recently fixed a few issues around microphone input, have you experienced this in the latest builds?

**Comment by nfriedly** [comment]
There does appear to be a firefox bug where mic audio can stop working after the browser has been open for a long time, but I don't think it's possible to fix or even detect in the demo.
