### ISSUE TITLE
cannot get "word_alternatives" from the result by using java sdk

### ISSUE THREAD

**Issue by Focuson-github** [watson-developer-cloud/speech-to-text-nodejs#119]
I want get "word_alternatives" from the result by using java sdk, but it does not work. Thus, i add some code to get  "word_alternatives". May I add some code to java sdk. Looking forward to your reply.

**Comment by germanattanasio** [comment]
Issue moved to [watson-developer-cloud/java-sdk #383](https://github.com/watson-developer-cloud/java-sdk/issues/383) via [**ZenHub**](https://www.zenhub.com/)
