### ISSUE TITLE
ffmpeg-node

### ISSUE THREAD

**Issue by tdhz77** [watson-developer-cloud/speech-to-text-nodejs#123]
I have an internal icecast stream that I would like to transcribe to text for the hearing impaired. 

Would it be possible to stream ffmpeg-node to watson?

**Comment by nfriedly** [comment]
Probably, try it out and let me know how it works! Although, this library is intended for web browsers. You'd want to use the node.js one: https://github.com/watson-developer-cloud/node-sdk

**Comment by nfriedly** [comment]
You'll probably want to skip this app and just start with the node.js SDK: https://github.com/watson-developer-cloud/node-sdk
