### ISSUE TITLE
Unable to run locally in chrome

### ISSUE THREAD

**Issue by kkorada** [watson-developer-cloud/speech-to-text-nodejs#125]
when i start application using node server,js, it is giving cors issue

```
GET https://stream.watsonplatform.net/speech-to-text/api/v1/models 
localhost/:1 XMLHttpRequest cannot load https://stream.watsonplatform.net/speech-to-text/api/v1/models. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 400.
```

**Comment by nfriedly** [comment]
Hi @kkorada,

I have a few questions to hopefully narrow things down:

That's in the browser console, right? Is there any other browser console output? What is the console output from the server?

How did you specify service credentials (.env file, environment properties, hard-coded into app.js, etc)? Are you sure you didn't accidentally swap the username and password (the username is longer).

Have you made any other changes?

**Comment by kkorada** [comment]
I have hard coded them directly into app.js and yes I have cross verified then username and password are  correct.

I have not done any other changes.

**Comment by nfriedly** [comment]
So, what do the browser & server logs show?

**Comment by kkorada** [comment]
it is showing **unable to get local issuer certificate** error. is it due to corporate firewall ?

**Comment by nfriedly** [comment]
Hi @kkorada,

Sorry this one slipped through the cracks; are you still experiencing this issue?

**Comment by nfriedly** [comment]
We've just launched a new demo that was just about re-written from scratch. If you're still experiencing this issue, then it may be due to a corporate firewall restriction.

I'm going to close this for now, but you can re-open if you can provide any more details.
