### ISSUE TITLE
Session closed. Reason: Payload exceeds the 104857600 bytes limit.

### ISSUE THREAD

**Issue by MichaelEvanchik** [watson-developer-cloud/speech-to-text-nodejs#127]
was it my file size?  it was 2 hours and a almost 600mb flac file and that was the message i had.

what can i do to fix this?

Session closed. Reason: Payload exceeds the 104857600 bytes limit.

**Comment by nfriedly** [comment]
Yep, the limit is about 100mb. You'll need to break your file up into smaller chunks or otherwise reduce the file size (convert stereo to mono, lower sample rate, lower bitrate, etc.)
