### ISSUE TITLE
Error : Required type for parameter "keywords_threshold" is float. Got type NoneType instead.

### ISSUE THREAD

**Issue by prasanta303** [watson-developer-cloud/speech-to-text-nodejs#130]
Just after selecting audio file, it's throwing above mentioned error. For, your information till 2 days back all those files giving STT output are now giving above mentioned error.
Please let me know what is wrong.

**Comment by daniel-bolanos** [comment]
Hi @prasanta303 , we fixed that a few hours ago, it should be fine now.
