### ISSUE TITLE
speech to text display : simple formatting

### ISSUE THREAD

**Issue by vaibhavagoel** [watson-developer-cloud/speech-to-text-nodejs#14]
Right now the text is treated as one long sentence.  Can we use pause duration, and mark a sentence boundary at >1 sec pause?

**Comment by germanattanasio** [comment]
I think we were doing that for the old demo. we were capitalize the sentence and put a .

**Comment by vaibhavagoel** [comment]
Yeah, that was better.  Could we put that in the new demo?  May not need to do a line break for every sentence, but at least a '.' and capitalize.

**Comment by germanattanasio** [comment]
Yes
