### ISSUE TITLE
Add support browsers on Iphone (Firefox, Chrome and Safari)

### ISSUE THREAD

**Issue by fe01134** [watson-developer-cloud/speech-to-text-nodejs#152]
This sample doesn’t support browsers on Iphone for recording voice? https://saywatson.mybluemix.net/  I just tried Chrome, Safari and Firefox.  On Iphone using safari,  Chrome and Firefox, it gives an error saying this browser doesn’t support microphone, I am however able to use the google microphone icon to speak to googles search engine.  Is this planned to be supported.  This same sample does work on Firefox on a Mac.

**Comment by fe01134** [comment]
Any update on this?

**Comment by germanattanasio** [comment]
@fe01134 Not all the mobile browsers have support for `getUserMedia()`. Looking at http://caniuse.com/#feat=stream It seems like Safari doesn't support it. Google could be using flash as a fallback. @nfriedly ?

**Comment by nfriedly** [comment]
It's not flash on iOS. For the Google microphone, are you talking about the one in the address bar in Chrome? That's native code, so the equivalent option would be using the [Swift SDK](https://github.com/watson-developer-cloud/swift-sdk) in your app.

This is basically an Apple limitation. They don't allow microphone access in Safari, and they don't *really* allow other browsers on iOS. (Firefox and Chrome for iOS are really just "skins" on Safari.)

This SDK should work perfectly on iOS as soon as Apple removes one of those restrictions. But we can't really do anything about it until then.

**Comment by fe01134** [comment]
Thanks.
