### ISSUE TITLE
Mac Record Audio issue

### ISSUE THREAD

**Issue by carlosaq** [watson-developer-cloud/speech-to-text-nodejs#155]
Hi, when tried to use the "Record Audio" button on the demo in Mac, I receive the next message "could not detect endianness after looking at the tail 0 non-zero byte string in a data stream of 144942 bytes. Is the bytestream really PCM data?". I tested on tree different Mac laptops and receive the same message, some ideas about how can solve it?

**Comment by nfriedly** [comment]
That's strange, it works reliably on my mac. What browser & version are you using?

Also, does this page work? https://watson-speech.mybluemix.net/microphone-streaming.html

**Comment by iankit3** [comment]
I think this is because you are not giving the speakers any input @carlosaq , Please check your microphone input then try and let us know .  :)

**Comment by germanattanasio** [comment]
I checked and it's working for me. Please reopen if that's not the case for you @carlosaq

**Comment by vperrinfr** [comment]
Hi, 
I have the same error on my Mac.
I have the same behavior on this page : https://watson-speech.mybluemix.net/microphone-streaming.html

1/ I have tested my "internal" microphone it works fine for other "native" apps on the mac. 
2/ I have tested with an external microphone and in that case it works fine. Audio is captured.

Any ideas ?

Thanks

**Comment by germanattanasio** [comment]
I think you need to update your browser.

**Comment by vperrinfr** [comment]
Problem solved.. I just updated to Version 60.0.3112.113 (Official Build) (64-bit) and it works fine now...

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
