### ISSUE TITLE
strange audio capture behavior in firefox

### ISSUE THREAD

**Issue by vaibhavagoel** [watson-developer-cloud/speech-to-text-nodejs#16]
In STT demo, pressing the microphone button to speak works fine the first time.  But if we press it to stop recording, and then press to start again, the STT output is very bad.  Looks like something wrong with audio capture the second time (and all subsequent attempts are bad too).  This is not an issue in Chrome, there it seems to work fine every time.

Testing Chrome and Firefox side by side, if I start/stop recording in both Chrome and Firefox, this seems to make Firefox work better - seemingly suggesting Chrome may be "initializing" something in audio capture that Firefox is not?

**Comment by germanattanasio** [comment]
I think it's related to the way we handle the memory when we create resources. We need to investigate

**Comment by germanattanasio** [comment]
@kasaby I realized that developers are using https://github.com/webrtc/adapter to avoid the cross browser problem were old versions of firefox are using `Navigator.getUserMedia` which is deprecated in the new versions.

**Comment by germanattanasio** [comment]
@kasaby did you try this: http://stackoverflow.com/questions/22860468/html5-microphone-capture-stops-after-5-seconds-in-firefox

**Comment by germanattanasio** [comment]
this was fixed long time ago.
