### ISSUE TITLE
Voice dropdown flicker

### ISSUE THREAD

**Issue by ehdsouza** [watson-developer-cloud/speech-to-text-nodejs#161]
The voice dropdown flickers causing the browser to hang during following scenarios:

Scenario 1:
Play Sample 1 => Stop it => Select a different voice model

Scenario 2:
Play Sample 1 => Select a different voice model

**Comment by nfriedly** [comment]
What browser? It seems to work for me in Firefox 55

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
