### ISSUE TITLE
Sample1 and Sample2 : transcription runs ahead of playback

### ISSUE THREAD

**Issue by vaibhavagoel** [watson-developer-cloud/speech-to-text-nodejs#17]
This looks 'magical' - we transcribe even before hearing the audio - makes it look like the whole thing is canned -:).  Can we pace the audio for our samples so that transcription follows the audio playback?  This is only for 'sample 1' and 'sample 2' (for all 6 models), not for general file upload where we do not know the sampling rate.

**Comment by germanattanasio** [comment]
@vaibhavagoel make sure you add a label so that I know if is a bug or an enhancement.

**Comment by vaibhavagoel** [comment]
Ok, will do.  Could we pl. look at this one soon.  Folks have been asking, this morning Manish Goyal was also saying he's been giving demos and it looks odd for the text to come before audio is played.  Thanks!

**Comment by germanattanasio** [comment]
Sorry @vaibhavagoel but I'm working on bugs right now. 
I rather prefer to fix the `500 forwarding error` bug in the nodejs wrapper.

**Comment by germanattanasio** [comment]
You think Dani can take a look ?

**Comment by vaibhavagoel** [comment]
Will ask Dani.  Can I somehow include him on this ticket?

**Comment by germanattanasio** [comment]
@daniel-bolanos can you help me with this?

**Comment by daniel-bolanos** [comment]
This is done already :)
