### ISSUE TITLE
Problem playing Text To Speech audio in IE11

### ISSUE THREAD

**Issue by johmca** [watson-developer-cloud/speech-to-text-nodejs#172]
Hi,

I have this working OK in Chrome but IE11 is not working for me.  Initially when using IE11 I was getting a prompt for logon credentials (not entirely sure what it was asking for? At some point I entered my T2S service credentials and I've not seen it since but that may be coincidence)

I logged the issue in Developer Works as
https://developer.ibm.com/answers/questions/418315/speech-to-text-working-ok-in-chrome-but-not-ie11.html?childToView=418318#answer-418318

![image](https://user-images.githubusercontent.com/23729693/33894257-6aaf8b96-df55-11e7-8630-75a9d110d6d7.png)

I was asked to raise the issue here.

Since logging the issue on DevWorks I tried a few things. I displayed controls on my audio element and it displays the message "Invalid Source" within the control which may be a clue.

The audio element HTML that is being used in the page has had its src attribute set programmatically and when I look at it in Chrome it appears as follows.

<audio class="audio" id="a_player" controls="controls" crossorigin="true" src="https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize?voice=en-GB_KateVoice&amp;text=I%20am%20a%20cognitive%20chatbot.%20I%20differ%20from%20other%20chatbots%20in%20that%20I%20use%20Machine%20Learning%20to%20understand%20you.%20I%20also%20understand%20the%20tone%20in%20your%20statements%20and%20respond%20accordingly.%20Call%20me%20a%20moron%20and%20you'll%20see%20what%20I%20mean!%20I%20am%20trained%20to%20converse%20on%20the%20subject%20of%%20report%20on%20AI%20which%20is%20available%20here.%20If%20I%20encounter%20something%20I%20have%20not%20been%20trained%20on%20I%20make%20a%20guess%20with%20an%20associated%20level%20of%20confidence.%20If%20my%20confidence%20is%20%20low%20I%20will%20ask%20you%20to%20rephrase%20your%20statement.%20Ask%20me%20more%20about%20myself.%20You%20could%20ask%20my%20name%2C%20why%20xxxxx%20built%20me%2C%20what%20subjects%20I%20can%20discuss%20or%20ask%20how%20xxxx%20built%20me%20if%20you%20are%20interested%20in%20learning%20how%20I%20work.&amp;watson-token=iMz6zjDjFV%2B5bDoIgjPtL6w4Llg0Y%2F0909uNRYPIU5uf1DixO8lP27obu3QnEG%2B3QKHWG9geJwDy5zgWib5tHIqlPSLFu2mcf3eHMhWLH5yBYxWYLKTneXiKxHQD%2BJ1S8XxHLTmZ8BOk6HLZX4Ok6plwxEvBpH9XH4dTwggPJicF1EVSlsRlHzBTcpKWM6V7kQ0m%2FA9zZtQTosGU1eLwV%2B%2F9a5%2FalQHmhEbNorr1g0Pqr8uvQAN7Rf8pKz%2BlRcUH5Zjx5VM49El46CYxmq8%2BU53GEOogh3WLdICCyF0xi9VBx%2Bqe69KSN8KNu4d0Ic6aKZWvEtS4CbuStNRpMKqow2OmlCAzYKAAjR%2FQXrobxJtIH6kMoz43GeSUO35fM3X6%2BeMFX0KCiyMRRgIBJ0HMZzMtr0nx0fgqEYBYripI9roCK4%2BW30jkKzb4dRwZpnNJknzmM%2Fj2ohM%2F5llPFrfTD5TQ7NNYUdd7jQz7erk2fF0jZr85r4igUsLtoYIW%2Bil5j7xG4rKN2YL0DDNybNWqOxTOJ3oMvLj1NwrasBtUEPHZRo3%2F5rG0mEKZUKiDaY3TXjIqFxPdb3bGiLrGWoznHQopSovcOcr8x%2BwlmQv78agxII1EBtkAiJ9fhda63iw3tzIKi3BXJWAsawT21R51l9NeL0YmYh1Sap24IeUuuABBPlgaIsLGlrvJhI0FYMjHlT0xeDoChTEin0AH8Kw36LlugyWCRZc6EUtie4i9n7DL9%2BMcMDpRy%2B4%2FWZJUH0Dg467xBAVAF%2FMszlkdepq9dmpFYo71VtfOA4xwtaxCUnMJmjx6nINcksOmfGvcpCf6iHUME7l0D9VIXDudT0Qf51PebIPZym1itf0zUBDCLFToLcUYBr6fj5uV5ZczadSD4o5qV0WbnJV4yudjcfBf0GDMIWZDntyFQ2RqVx6KN9eJDygKjWwOPMiY%2Fh6FTQ%2FNfUBULLNwURl%2BAuAlWMmIXLw6TDYooNoY">
Your browser does not support the audio element.
</audio>

**Comment by germanattanasio** [comment]
@anweshan can you look at this?

**Comment by johmca** [comment]
Actually I did get it working in the end (updated in DevWorks but must have forgotten about here). It seems default format is OGG and this is not supported in IE11. Switched to MP3 and it was OK. for both Chrome and IE11 Don't now what the original problem was with the login request but it stopped requesting it.

**Comment by germanattanasio** [comment]
Great. I'm closing this then. Feel free to reopen.
