### ISSUE TITLE
How can i get the spooken text into Java?

### ISSUE THREAD

**Issue by BenediktGoos** [watson-developer-cloud/speech-to-text-nodejs#173]
I know the question is not very difficult, but i have a problem to get the spoken text. Can somebody show me how i can get the text into java or knows where i can find the function which write the spoken text?
Thank you very much

**Comment by germanattanasio** [comment]
Hi @BenediktGoos take a look at the https://github.com/watson-developer-cloud/java-sdk repository. There is an example folder where you can find examples of how to use the Speech to Text service
