### ISSUE TITLE
use the browser's resampler rather than writing your own in JS

### ISSUE THREAD

**Issue by ArthurKantor** [watson-developer-cloud/speech-to-text-nodejs#18]
Using the offlineaudiocontext for resampling as in https://stream.watsonplatform.net/speech-to-text/api/v1/websocketClient (specifically, in https://stream.watsonplatform.net/speech-to-text/api/v1/static/mic.js from August 1,2015) might be more efficient and less magical.

**Comment by germanattanasio** [comment]
@ArthurKantor I think this is an enhancement. In that case can you please provide more details about the changes you want us to do?

**Comment by ArthurKantor** [comment]
yes, it's not a defect.  I see now I can add labels - thanks for changing it.  

The details:
Instead of using a filter in https://github.com/watson-developer-cloud/speech-to-text-nodejs/blob/master/src/Microphone.js#L179-214 which is computationally intensive, use the [offlineaudiocontext]( https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext) as  in mic.js in the top of the thread, which should be done by the browser rather than in javascript.  

This is not a critical thing, but may help battery life on mobile devices.

**Comment by daniel-bolanos** [comment]
I implemented this already, but left if commented out in the code, since it is not compatible with older versions of Chrome. In particular with the one I have installed :)

**Comment by germanattanasio** [comment]
Should we close this @daniel-bolanos ?
