### ISSUE TITLE
Only .wav files can be uploaded in Safari

### ISSUE THREAD

**Issue by kkeerthana** [watson-developer-cloud/speech-to-text-nodejs#183]
Only .wav files can be uploaded in Safari; it doesn't let me upload the other stated formats (.mp3, .mpeg, .flac, or .opus).
All formats work fine in Chrome & Firefox.

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/8869904/36611090-5212f558-18a0-11e8-9171-96f056cd48cd.png">

**Comment by germanattanasio** [comment]
I can't reproduce this. I just tested with a wav, ogg, flac, and an mp3 file
