### ISSUE TITLE
Sample Audio File not working

### ISSUE THREAD

**Issue by rowed** [watson-developer-cloud/speech-to-text-nodejs#19]
See question on Dev Works: https://developer.ibm.com/answers/questions/205005/speech-to-text-demo-play-sample-audio-not-working.html

Steps Taken:
1. Click 'Deploy to Bluemix' Button in the README file
2. Click through to deploy application in my own bluemix space
3. Click route (http://speech-to-text-deploybutton.mybluemix.net/) then click any of the options (record audio, upload file, play sample 1, play sample 2) and there is no response. 

There is most likely a step I'm forgetting here, but I appreciate any help you can provide.

**Comment by germanattanasio** [comment]
I just tested and everything seems to be working fine
