### ISSUE TITLE
 Add GDPR Language to Stand Alone Demo Pages

### ISSUE THREAD

**Issue by mamoonraja** [watson-developer-cloud/speech-to-text-nodejs#192]
**Context:**
GDPR will go into effect on May 25th; we need the demos to display the following language in order to make them compliant with the law:

`This system is for demonstration purposes only and is not intended to process Personal Data. No Personal Data is to be entered into this system as it may not have the necessary controls in place to meet the requirements of the General Data Protection Regulation (EU) 2016/679.`

For more information see: https://github.ibm.com/Watson/developer-experience/issues/4342

**Comment by kemerson16** [comment]
@daniel-bolanos Can you please confirm you've seen this request and will be able to make the necessary changes before 5/25? Thx

**Comment by kemerson16** [comment]
@mbouldin Appreciate your assistance in tracking this work for completion as part of the GDPR requirements being tracked by Rob here https://github.ibm.com/watson-foundation-services/GDPR/issues/3

**Comment by mbouldin** [comment]
@kemerson16 absolutely, we covered this in our team meeting today as well, we will get back to you.

mention - @arl

**Comment by mamoonraja** [comment]
Done in https://github.com/watson-developer-cloud/speech-to-text-nodejs/pull/193

**Comment by mbouldin** [comment]
@kemerson16 ^^^
