### ISSUE TITLE
Speaker Issue

### ISSUE THREAD

**Issue by IAmVinnnn** [watson-developer-cloud/speech-to-text-nodejs#195]
I was transcript an audio file in which only one person speak but in the response I got 3 speaker. Is there anything I need to fix at my end?

**Comment by jeffpk62** [comment]
@IAmVinnnn Take a look at this section of the documentation:  [Speaker Labels](https://console.bluemix.net/docs/services/speech-to-text/output.html#speaker_labels).

It documents the speaker labels feature but also describes some of the oddities that you may encounter in speaker labels results.  The interface is still beta at this time, and its recognition of speakers is not perfect. It can identify extra speakers based on the audio that it encounters.  Specifically, under "Performance considerations," the documentation states

_Performance for audio with a single speaker can be poor. Variations in audio quality or in the speaker's voice can cause the service to identify extra speakers who are not present. Such speakers are referred to as hallucinations._

So what you're seeing may just be an unavoidable artifact of the audio for a single speaker.  Audio quality can help performance, so if there is any way to ensure cleaner input, you might try that.

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
