### ISSUE TITLE
Easy example node + express?

### ISSUE THREAD

**Issue by vin-ni** [watson-developer-cloud/speech-to-text-nodejs#197]
Hi,
Is there a simpler node example than the provided one?
I'm just playing around with a simple node.js + express boilerplate and find it quite difficult implementing your example which is built on react.

**Comment by germanattanasio** [comment]
We are using React because of the features and interactions we want to show in the demo.

What are you trying to do with the service? If you are just planning on doing some recognitions try to look at the examples here: https://github.com/watson-developer-cloud/speech-javascript-sdk

**Comment by vin-ni** [comment]
Ah alright, I'll take a look at this! Thanks!
