### ISSUE TITLE
Information : where is the UI defined ? 

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/speech-to-text-nodejs#198]
Hello, The app is working ok for me. I 'd like to modify the user interface. 
Unfortunately, I haven't been able to find the place where to do that ; 
There are a few minor elements in the file views/layout.jsx, but most of the text mentions are inaccessible to me.
Can you point me to the places where those elements are?
Thank you

**Comment by germanattanasio** [comment]
All the UI is in the `views` folder: https://github.com/watson-developer-cloud/speech-to-text-nodejs/tree/master/views

The code is React, if you are not familiar with react I would suggest you look at the website https://reactjs.org/tutorial/tutorial.html
