### ISSUE TITLE
Unable to add spaces or commas in the "keywords to spot" box

### ISSUE THREAD

**Issue by kkeerthana** [watson-developer-cloud/speech-to-text-nodejs#207]
I'm not able to enter a comma-separated list of keywords to spot. Spaces and commas don't seem to be accepted here:

![image](https://user-images.githubusercontent.com/8869904/43739755-205e0f8e-9997-11e8-83bb-fef9885b73b1.png)

Copying text with commas/spaces into the box works fine.

**Comment by germanattanasio** [comment]
Fixed in 20226dd
