### ISSUE TITLE
Error retrieving auth token

### ISSUE THREAD

**Issue by daviadenisco** [watson-developer-cloud/speech-to-text-nodejs#216]
My apikey and url are entered correctly in a .env file but when I run it, I get Error retrieving auth token. Tried including the speech to text username with the api key as the pword but that doesn't work either. Any suggestions as to what might be causing the error? Thanks!

**Comment by germanattanasio** [comment]
Make sure your `.env` file has the IAM apikey. It should look like the example below

```
SPEECH_TO_TEXT_IAM_APIKEY=X4rbi8vwZmKpXfowaS3GAsA7vdy17Qh7km5D6EzKLHL2
SPEECH_TO_TEXT_URL=https://stream-wdc.watsonplatform.net/speech-to-text/api
```

Don't use `USERNAME` or `PASSWORD`

**Comment by akeller** [comment]
Did exactly that. Looks like there are platform issues this morning, at least with my account. I'm not able to access my services in the dashboard. I'll retry and keep you updated.

**Comment by daviadenisco** [comment]
Got it to work by commenting out the SPEECH_TO_TEXT_IAM_URL. Didn't realize only one URL should be in the file since the last one is labeled "Service URL", figured that URL was needed for some other reason. Thanks germanattanasio!

Example of what the .env file should look like:

# Environment variables
# You need to provide either username and password
# SPEECH_TO_TEXT_USERNAME=
# SPEECH_TO_TEXT_PASSWORD=
# OR IAM API key and URL
SPEECH_TO_TEXT_IAM_APIKEY=X4rbi8vwZmKpXfowaS3GAsA7vdy17Qh7km5D6EzKLHL2
# SPEECH_TO_TEXT_IAM_URL=https://gateway-wdc.watsonplatform.net/speech-to-text/api
# Service URL
SPEECH_TO_TEXT_URL=https://stream-wdc.watsonplatform.net/speech-to-text/api
