### ISSUE TITLE
Split front-end code into a library

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/speech-to-text-nodejs#22]
First off, this is an awesome demo and you guys did a great job on it.

That said, the front-end code is fairly complex and I think that at least part of it probably belongs in a library that we stick in bower and/or npm and then just reference it here. 

That would ease developing new application because it would be something that one could simply drop in and have a clear line of "what code I can reuse without thinking about it" vs "what code I need to write for myself".

**Comment by germanattanasio** [comment]
I think that was the idea that @esbullington had when he wrote it.

**Comment by daniel-bolanos** [comment]
Yes, I suggested him to do that, I wanted us to build a JS object for STT and another one for TTS, following the speech of the W3C https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html
Basically encapsulate all the low level details so the developer does not need to deal with that. 

We definitely need to refactor the code and produce those JS objects to make the developers life a lot easier. We will do it when we find some time...

**Comment by nfriedly** [comment]
Cool, just wanted to throw it out there.

**Comment by daniel-bolanos** [comment]
Thank you @nfriedly, we appreciate the feedback.

Dani

**Comment by germanattanasio** [comment]
This is being implemented #86.

**Comment by nfriedly** [comment]
This is done, lib is at https://github.com/watson-developer-cloud/speech-javascript-sdk, and this demo is now using the lib under the hood.
