### ISSUE TITLE
MediaStream.stop() deprecated in Chrome

### ISSUE THREAD

**Issue by hakanson** [watson-developer-cloud/speech-to-text-nodejs#33]
When running this sample on Chrome Version 45.0.2454.101 (64-bit) for Mac OS, I get the following message on the JavaScript console from file `Microphone.js`

`'MediaStream.stop()' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.active' instead.`

**Comment by germanattanasio** [comment]
fixed
