### ISSUE TITLE
Merge livedemo with master and use an environment variable to configure rate-limiting and CSRF

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/speech-to-text-nodejs#34]

**Comment by daniel-bolanos** [comment]
@germanattanasio we are going to leave one for you since you added those features to the live demo, is that fine?

thank you

Dani

**Comment by germanattanasio** [comment]
yes I will handle this! thanks @daniel-bolanos

**Comment by germanattanasio** [comment]
fixed in 0845bad0429199018a2712d0361b1cc4f6653e28
