### ISSUE TITLE
it dosen't work on mobilephone

### ISSUE THREAD

**Issue by Camixxx** [watson-developer-cloud/speech-to-text-nodejs#40]
The microphone dosen't work when I used ipad or andorid to test the demo.Could it be the browser's problem?We hope not.😱😱😱😱😱

**Comment by nfriedly** [comment]
For the iPad, it was definitely the browser's problem, Safari on IOS doesn't give microphone access, and Apple doesn't allow for other browsers (except ones that are really just Safari wrappers). I believe that some Android browsers do, but definitely not all - can you specify what browser/Android version you tried?.

**Comment by daniel-bolanos** [comment]
Hello @Camixxx , I have tried on a number of Android devices, using Chrome, and the microphone component does not capture the audio right, it comes out corrupted, so the STT demo wont work.

We have released mobile SDKs (Android and iOS) to interact with both STT and TTS services, you can find them here:

https://github.com/watson-developer-cloud/speech-ios-sdk
https://github.com/watson-developer-cloud/speech-android-sdk

Dani

**Comment by nfriedly** [comment]
BTW @daniel-bolanos & @Camixxx, I just tested in Chrome and Firefox on my Android phone and had success in each - it correctly transcribed all of my test phrases. 

The only issue I saw is that Firefox keeps the "Microphone is on" notification even after I stop recording. In Firefox, the notification only went away when I closed the tab, whereas Chrome correctly removes the notification as soon as I stop the recording.

My phone is a Verizon HTC One M8 running:
Android 5.1.1 (CyanogenMod 12.1-20150925-NIGHTLY-m8)
Firefox 41.0.2
Chrome 46.0.2490.76

**Comment by daniel-bolanos** [comment]
hi @nfriedly , really? Hmm in the past every time I tried from Chrome in my Android the recognition results were very poor, then I would listen to the audio file recorded and was always corrupt. What phone are you using? is it last generation?

Regarding that notification issue, I think I have seen that even in my ubuntu... will need to look into that. Maybe we are not releasing something.

thanks for feedback :)

**Comment by nfriedly** [comment]
@daniel-bolanos this phone: http://pdadb.net/index.php?m=specs&id=5890&c=verizon_htc_one_m8_2014_lte-a_htc6525lvw_htc_m8 - about 1.5 years old, so previous generation.

And I should clarify that I didn't get *perfect* transcription, but generally pretty good, on par with what I get from my macbook.
