### ISSUE TITLE
Show the playback when the url contains a debug=true or 1

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/speech-to-text-nodejs#59]
We should hide/show the playback button if the url contains a specific query parameter like `debug` or `playback`

This will be really useful for users trying to test their microphone. They will be able to see what are they sending to the service.

I would suggest to use `debug` since that will allow us to do more than just playback.
```
speech-to-text-demo.mybluemix.net?debug=true
```

@kasaby you have already implemented the playback functionality. Can you detect the query parameter and show/hide it?

**Comment by kasaby** [comment]
ok I'm working on it.

**Comment by kasaby** [comment]
https://github.com/watson-developer-cloud/speech-to-text-nodejs/pull/63
done.

**Comment by germanattanasio** [comment]
@daniel-bolanos can you test and deploy the latest changes
