### ISSUE TITLE
STT : main text window scroll to show most recent text

### ISSUE THREAD

**Issue by vaibhavagoel** [watson-developer-cloud/speech-to-text-nodejs#8]
At the moment when text overflows in the main text window, users have to scroll down to see most recent text.  Could we keep the text window always scrolled to bottom, showing most recently recognized text?  Thanks, Vaibhava

**Comment by germanattanasio** [comment]
Fixed in 9840f7630aeca70598e3f6c96cf427dcb04a76f7
