### ISSUE TITLE
[speech-to-text]  1006 Connection dropped by remote peer.

### ISSUE THREAD

**Issue by monte-hayward** [watson-developer-cloud/speech-to-text-nodejs#80]
I'm testing files of roughly 75MB through the Websocket route.
After weeks of working consistently, today I am getting the message:
  `1006 Connection dropped by remote peer.`
This is occurring immediately, with no result messages.

```
About to send ./in/1861034_xxx_lp.f4v-part000.flac
connect. config is {"maxReceivedFrameSize":1048576,"maxReceivedMessageSize":8388608,"fragmentOutgoingMessages":true,"fragmentationThreshold":16384,"webSocketVersion":13,"assembleFragments":true,"disableNagleAlgorithm":true,"closeTimeout":5000,"tlsOptions":{}}
1006 Connection dropped by remote peer.
```
Is this issue something to report here, or to another ticketing system for the S2T service itself?

**Comment by monte-hayward** [comment]
Happens also for various-sized files -- 11MB, 21MB, 37MB

**Comment by monte-hayward** [comment]
parameters that I am using have not changed in awhile:

```
{
    content_type: self.options.contenttype,
    'content-type': self.options.contenttype,
    base_url: credentials.url,
    continuous: true,
    timestamps: true,
    inactivity_timeout: -1,    // -1 means Infinity
    max_alternatives: 1,
    interim_results: true,
    keywords: KEYWORDS,               // beta feature
    keywords_threshold: 0.9,          // beta feature
    word_alternatives_threshold: 0.25,  // beta feature
    objectMode: true,                   // wishful
    readableObjectMode: true
  };
```

**Comment by daniel-bolanos** [comment]
Hello @monte-hayward we are aware of this issue an trying to resolve it asap, sorry for the inconvenience. 

Dani

**Comment by monte-hayward** [comment]
Thanks!

**Comment by daniel-bolanos** [comment]
@monte-hayward  please try now, the STT service is fully functional now :)

**Comment by monte-hayward** [comment]
@daniel-bolanos thanks!

Semi-related question:
https://developer.ibm.com/answers/questions/249101/patterns-for-watsonauthorization-tokens-in-node-mo.html
