### ISSUE TITLE
No/wrong error message on Safari

### ISSUE THREAD

**Issue by jeffeisen** [watson-developer-cloud/speech-to-text-nodejs#84]
I realize this isn't supported on Safari, but when trying demo on the Mac under Safari, when I click "Record Audio", nothing happens (no error message) and when I think click on something else (like Play Sample), I get "Currently audio is being record...".

The "Record Audio" should probably be grayed out if not supported

**Comment by ChrisCinelli** [comment]
The first problem that I found on Safari was complaining about `const` not being supported in strict mode. I replaces all `const` with `var` in `displaymetadata.js` and that fixed the `const` problem. The next thing is complaining about : WebSocket connection to `wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?watson-token=XXXXXX&model=en-US_BroadbandModel' failed: Invalid UTF-8 sequence in header value`

**Comment by zeusorion** [comment]
any updates on the fix for the bug complaining `failed: Invalid UTF-8 sequence in header value` on Safari?

**Comment by germanattanasio** [comment]
We are updating the demo with a new layour. See the *react* branch. This
will get fix once we have that demo ready.

**Comment by zeusorion** [comment]
Checkout out the *react* branch, Chrome seems fine. Safari is not functioning. 
I made the appropriate config changes to add the watson voice credentials to run it locally. 

The React demo makes use of the `fetch( )` api which is not supported by Safari. Not able to see how the `wss` issue is resolved. 

Fetch API: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

Is there a working example on Safari?

**Comment by nfriedly** [comment]
I believe a workaround for the safari "Invalid utf-8..." bug will be included in an upcoming release of the service. After that is in place, we can look into what else is required for Safari compatibility.

**Comment by nfriedly** [comment]
Actually, I just pushed an update to the react branch:

1. It adds the fetch pollyfill for safari/IE (in anticipation of the service's upcomming workaround for safari websocket bugs).
2. It displays a clear error for mic input on browsers that don't support it.

It still doesn't work in Safari but it does give better error messages now, and file playback may work once the service update is release.
