### ISSUE TITLE
Extra and confusing .js files in projects

### ISSUE THREAD

**Issue by biosopher** [watson-developer-cloud/speech-to-text-nodejs#98]
It appears the public/flash and public/js folders are not necessary and should be removed.  The microphone code seems to have been migrated to src/Microphone.js and related files.  Took awhile to determine those extra folders weren't used anymore.

Thanks

**Comment by biosopher** [comment]
OK...I see that the public/js is built by Browserify.  Would be nice if it was in .gitignore, but no biggie.  It does lead the savvy user to realize Browserify is being used.  Still seems the public/flash directory is not in use though.

**Comment by nfriedly** [comment]
Hi @biosopher 

I just made a couple of changes that should address this:
* the browserify JS bundle is now generated on demand and only stored in memory, not on disk. So no public/js folder
* I removed the public/flash folder

I'm also working on some other changes to clean up and simplify this demo.

**Comment by biosopher** [comment]
Thanks Nathan.  Great work on this DSK for WDC!
